version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pruebas
    ports:
      - "5432:5432"
    #volumes:
    #  - ./postgres:/var/lib/postgresql/data