version: "3"
services:
  postgres:
    image: "postgres:9.6"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prueba
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data